### ISSUE TITLE
 If AndroidP7zip supports these feature

### ISSUE THREAD

**Issue by asthagarg2428** [hzy3774/AndroidP7zip#29]
Hi,
It's not an issue though, want to check if Android7zip supports following features or not:

- Check if it use 3rd party lib /External dependencies
- Can Extract
- Can Compress
- Can Read
- Can Write
- Add entries in zip
- Remove entries from zip
- Can Handle Password Protection
- Can support different languages
- Can Handle File size > 4GB (check this)
- In-memory archive

Also, what will be the the approximate size increase after using this library and how is the performance?

Looking forward for quick reply :)

**Comment by huzongyao** [comment]
it's the wrapper of p7zip, please just check http://p7zip.sourceforge.net/

**Comment by asthagarg2428** [comment]
@huzongyao How can I support a password protected zip and 7zip files? 
Which command do I need for that?
